name: GitHub Pages

on:
  push:
    branches:
      - feature/test-publish-html
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: toronto-cli install & run
        env:
          TORONTO_CLI_VERSION: 1.0.0
          MOT_TORONTO_TOKEN: ${{ secrets.MOT_TORONTO_TOKEN }}
        run: |
          # install toronto-cli
          curl -LO https://toronto-cli-5d506707-9097-443c-bbf7-f15775d84c68.s3.ap-northeast-1.amazonaws.com/${TORONTO_CLI_VERSION}/toronto-cli-linux-386.tar.gz
          tar -xzf toronto-cli-linux-386.tar.gz
          mv toronto-cli-linux-386 toronto-cli
          chmod +x toronto-cli
          rm -r toronto-cli-linux-386.tar.gz
          # run toronto-cli
          ./toronto-cli
      - uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: true
          enable_jekyll: true

      - name: deploy
        uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000


