name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: toronto-cli install & run
        env:
          TORONTO_CLI_VERSION: 1.0.0
          MOT_TORONTO_TOKEN: ${{ secrets.MOT_TORONTO_TOKEN }}
        run: |
          # install toronto-cli
          curl -LO https://toronto-cli-5d506707-9097-443c-bbf7-f15775d84c68.s3.ap-northeast-1.amazonaws.com/${TORONTO_CLI_VERSION}/toronto-cli-linux-386.tar.gz
          tar -xzf toronto-cli-linux-386.tar.gz
          mv toronto-cli-linux-386 toronto-cli
          chmod +x toronto-cli
          rm -r toronto-cli-linux-386.tar.gz
          # run toronto-cli
          ./toronto-cli

